-- VeriPay database schema.
-- Paste into the Supabase SQL editor of a fresh project and run it once.
--
-- Every table has row-level security ON and no policies: nothing is readable
-- with the public anon key. The app only ever talks to the database from the
-- server, with the service-role key.

-- ─── Pay links (built during Metropolis) ────────────────────────────────────

create table if not exists sellers (
  handle     text primary key check (handle ~ '^[a-z0-9][a-z0-9_-]{2,29}$'),
  name       text not null check (char_length(name) between 2 and 60),
  address    text not null unique check (address ~ '^0x[a-f0-9]{40}$'),
  created_at timestamptz not null default now()
);

create table if not exists pay_intents (
  id             text primary key,
  handle         text not null references sellers(handle),
  seller_address text not null,
  buyer_address  text not null,
  amount_ngn     numeric not null check (amount_ngn > 0),
  item           text not null,
  email          text not null,
  status         text not null default 'awaiting_payment'
                 check (status in ('awaiting_payment', 'paid', 'funded', 'failed')),
  paystack_ref   text unique,          -- one card charge can fund one payment only
  mint_tx        text,                 -- 'pending' while delivery is in flight
  test_mode      boolean not null default false,
  created_at     timestamptz not null default now(),
  paid_at        timestamptz
);
create index if not exists pay_intents_buyer_idx on pay_intents (buyer_address);

-- ─── Notifications, chat, push ──────────────────────────────────────────────

create table if not exists notifications (
  id           bigint generated by default as identity primary key,
  to_address   text not null,
  type         text not null check (type in ('trade', 'chat')),
  trade_id     text not null,
  from_address text not null,
  amount       text,
  message      text,
  read         boolean not null default false,
  created_at   timestamptz not null default now()
);
create index if not exists notifications_to_address_idx on notifications (to_address, created_at);

create table if not exists chat_messages (
  id         bigint generated by default as identity primary key,
  thread_id  text not null,
  sender     text not null,
  address    text not null,
  message    text not null,
  is_admin   boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists chat_messages_thread_idx on chat_messages (thread_id, created_at);

create table if not exists push_subscriptions (
  id         bigint generated by default as identity primary key,
  address    text not null,
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  created_at timestamptz not null default now()
);
create index if not exists push_subscriptions_address_idx on push_subscriptions (address);

-- ─── Trade log (a convenience mirror; the chain is the source of truth) ─────

create table if not exists escrow_trades (
  trade_id               bigint primary key,
  buyer_address          text not null,
  seller_address         text not null,
  amount_wei             text not null,
  metadata               text,
  status                 text not null default 'locked' check (status in ('locked', 'refund_ready', 'settled')),
  create_tx_hash         text,
  release_tx_hash        text,
  refund_approve_tx_hash text,
  refund_claim_tx_hash   text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);
create index if not exists escrow_trades_status_idx on escrow_trades (status);
create index if not exists escrow_trades_buyer_idx  on escrow_trades (buyer_address);
create index if not exists escrow_trades_seller_idx on escrow_trades (seller_address);

create table if not exists trade_activity (
  id            bigint generated by default as identity primary key,
  trade_id      bigint not null,
  actor_address text not null,
  action        text not null check (action in ('created', 'released', 'refund_approved', 'refund_claimed')),
  tx_hash       text,
  created_at    timestamptz not null default now()
);
create index if not exists trade_activity_trade_idx on trade_activity (trade_id);

-- ─── Naira exchange (pre-hackathon) ─────────────────────────────────────────

create table if not exists exchange_orders (
  id                  text primary key,
  side                text not null check (side in ('buy', 'sell')),
  coin                text not null,
  coin_name           text,
  amount_crypto       numeric not null,
  amount_ngn          numeric not null,
  rate                numeric,
  fee_ngn             numeric,
  wallet_address      text not null,
  bank_name           text,
  bank_account_number text,
  bank_account_name   text,
  status              text not null default 'awaiting_payment'
                      check (status in ('awaiting_payment', 'payment_review', 'verified', 'confirming',
                                        'completed', 'rejected', 'expired', 'cancelled')),
  settlement_ref      text not null,
  created_at          timestamptz not null default now(),
  paid_at             timestamptz,
  tx_hash             text,
  payout_tx_hash      text,
  payment_method      text not null default 'transfer' check (payment_method in ('transfer', 'card')),
  exact_amount_ngn    numeric,
  base_rate           numeric,
  spread_percent      numeric,
  quote_expires_at    timestamptz,
  payer_name          text,
  payer_note          text,
  paystack_ref        text,
  payout_ref          text,
  admin_note          text,
  rejection_reason    text,
  verified_at         timestamptz,
  released_at         timestamptz,
  reviewed_at         timestamptz
);
create index if not exists exchange_orders_wallet_idx on exchange_orders (wallet_address);
create index if not exists exchange_orders_status_idx on exchange_orders (status);
create index if not exists exchange_orders_side_idx   on exchange_orders (side);
-- A deposit transaction or a card charge can settle one order only.
create unique index if not exists exchange_orders_tx_hash_key      on exchange_orders (lower(tx_hash)) where tx_hash is not null;
create unique index if not exists exchange_orders_paystack_ref_key on exchange_orders (paystack_ref)   where paystack_ref is not null;

create table if not exists exchange_order_events (
  id         bigint generated by default as identity primary key,
  order_id   text not null,
  actor      text not null,
  action     text not null,
  detail     text,
  created_at timestamptz not null default now()
);
create index if not exists exchange_order_events_order_idx on exchange_order_events (order_id, created_at desc);

-- ─── Analytics ──────────────────────────────────────────────────────────────

create table if not exists app_users (
  wallet_address text primary key,
  connect_count  integer not null default 1,
  last_seen_at   timestamptz not null default now(),
  created_at     timestamptz not null default now()
);

create table if not exists wallet_events (
  id             bigint generated by default as identity primary key,
  wallet_address text not null,
  event_type     text not null,
  user_agent     text,
  created_at     timestamptz not null default now()
);
create index if not exists wallet_events_type_created_idx on wallet_events (event_type, created_at);
create index if not exists wallet_events_wallet_idx       on wallet_events (wallet_address);

create table if not exists page_views (
  id             bigint generated by default as identity primary key,
  path           text not null,
  wallet_address text,
  referrer       text,
  created_at     timestamptz not null default now()
);
create index if not exists page_views_created_idx on page_views (created_at);
create index if not exists page_views_wallet_idx  on page_views (wallet_address);

-- ─── Lock everything down ───────────────────────────────────────────────────

alter table sellers               enable row level security;
alter table pay_intents           enable row level security;
alter table notifications         enable row level security;
alter table chat_messages         enable row level security;
alter table push_subscriptions    enable row level security;
alter table escrow_trades         enable row level security;
alter table trade_activity        enable row level security;
alter table exchange_orders       enable row level security;
alter table exchange_order_events enable row level security;
alter table app_users             enable row level security;
alter table wallet_events         enable row level security;
alter table page_views            enable row level security;
